Post http://localhost:8000/videos
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Este é o vídeo 02",
    "duration": "120"
}

###

get http://localhost:8000/videos


###

get  http://localhost:8000/videos?search=node


###

PUT  http://localhost:8000/videos/57684040-ce41-41d6-989a-72617342c0aa
Content-Type: application/json

{
    "title": "Video 03",
    "description": "Este é o vídeo 03",
    "duration": 120
}


###

DELETE  http://localhost:8000/videos/d0be2ba7-adc9-4ec9-8904-f87633cd2c20
